### ISSUE TITLE
Aos Sword Pallete Problem

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#11]
I found a problem
when trying to change the color of the hruting sword palette
the game crashes and I can no longer access the palette through the sprit editor '-'

**Comment by LagoLunatic** [comment]
Using DSVEdit 1.8.1 I edited the hrunting's palette at random and it runs fine:
![aos hrunting palette](https://user-images.githubusercontent.com/19174152/64998594-cad13f80-d8b2-11e9-9c9e-40aa5dc487a1.png)

You must have done something else to cause this crash. Perhaps some other edit you made to the game unrelated to hrunting is the cause, and you just thought it was the hrunting palette due to doing them around the same time? There's no reason editing a palette should make the game crash.

See if you can reproduce this on a clean AoS rom somehow, and if you can tell me how to do it.
If you can't do it, make an IPS patch of the broken AoS rom and upload the IPS patch here and I'll look into it.

**Comment by Urahara666** [comment]
man i'm trying to change the maximum life value of the sum that is 1496, i know this is no place for questions and so i have my email to contact, i am not using dsedit but a hex editor for that.
and please don't close the discussion

**Comment by Urahara666** [comment]
with 1.8.1 version it works, thanks

**Comment by LagoLunatic** [comment]
>man i'm trying to change the maximum life value of the sum that is 1496

I still really can't understand you. You aren't giving any details and you're asking me to make wild guesses about what you're trying to do.
I decided to google it - apparently 1496 is Soma's max HP at level 99? So you want to change how much HP gets added to Soma's max every time he levels up... I think?
If that's the case you should use no$gba's debugger to find the code that increases Soma's HP when he levels up, and then write an ASM patch to modify that code to do what you want.

**Comment by LagoLunatic** [comment]
>with 1.8.1 version it works, thanks

That's good

**Comment by Urahara666** [comment]
> > man i'm trying to change the maximum life value of the sum that is 1496
> 
> I still really can't understand you. You aren't giving any details and you're asking me to make wild guesses about what you're trying to do.
> I decided to google it - apparently 1496 is Soma's max HP at level 99? So you want to change how much HP gets added to Soma's max every time he levels up... I think?
> If that's the case you should use no$gba's debugger to find the code that increases Soma's HP when he levels up, and then write an ASM patch to modify that code to do what you want.

I already managed to change what I wanted, and thanks so much for the dsvania tool
it's an amazing tool
