### ISSUE TITLE
Sprite Editor's "import from darkFunction" is broken

### ISSUE THREAD

**Issue by piratesephiroth** [LagoLunatic/DSVEdit#16]
- I used DSVEdit v1.8.1
- I only tested on Dawn of Sorrow
- issue happens even if the data is re-imported without changes

The import process isn't setting up the frames and parts correctly if the sprite uses more than 1 GFX page.

**Comment by LagoLunatic** [comment]
I tried on Peeping Eye in DoS (which has 2 GFX pages) and it seems to work correctly. It imports as expected if I modify the animation frames, or the parts, and also if I don't modify anything and immediately re-import it.

Some more information that might help me reproduce it: What exact sprite are you modifying? What edits are you making to the sprite? Uploading the three files (.anim .png and .sprites) after you've modified them with darkfunction might help.

**Comment by piratesephiroth** [comment]
It happened with multiple sprites including Peeping Eye
Notice that it has 0x4E parts. Export and re-import and it now has 0x4C.

The more pages the sprite has, the bigger the problem becomes, affecting also the frame count.
Try with a playable character and you'll see it breaks nearly all of their animations.

I decided to test older versions and saw it worked fine on v1.7.1
https://cdn.discordapp.com/attachments/490497701398577162/651828209469489163/Action_04-12-2019_13-46-58.mp4

**Comment by LagoLunatic** [comment]
Huh, dang, I must've screwed something up when I refactored stuff to work with fileless sprites for 1.8.0.
Seems to also affect Death and Bat Company.

The Peeping Eye thing seems like it could be a different bug. It only deleted the parts for two frames, 24 and 25, instead of screwing up the order of basically all frames and animations and deleting some frames. And 1.7.1 still deleted parts for those two frames as well.

**Comment by piratesephiroth** [comment]
Here's my files (Julius's with the running animation from Harmony of Despair) just in case you want to try reimporting modified data.

[DoS_julius_RUN.zip](https://github.com/LagoLunatic/DSVEdit/files/3923257/DoS_julius_RUN.zip)

**Comment by LagoLunatic** [comment]
Turns out it was caused by the presence of "unanimated animations", when I added support for those I must not have tested it on the DS games very much because I forgot about a quirk of how sprite keyframes are read there.

Also, for the Peeping Eye thing, turns out that's not a bug at all. Peeping Eye's vanilla sprite just has some duplicate frames used in animations, and my darkFunction importer merges all duplicates so it resulted in frames 24 and 25 being "deleted" (not literally deleted since that would screw stuff up, just their parts are deleted).
