### ISSUE TITLE
DoS - Reimported NPC sprite gets stuck in cutscene

### ISSUE THREAD

**Issue by piratesephiroth** [LagoLunatic/DSVEdit#28]
A reimported Arikado Event Actor gets stuck in the prologue, at the moment he should throw the knife to Soma.
I examined the sprite file and didn't find any relevant hidden data so it's something caused by the "optimizations" the program applies while reimporting.
So maybe the game's event code uses a hardcoded offset to a frame or animation?

It's easy to reproduce it, Just export to darkfunction and reimport back without changes.

**Comment by LagoLunatic** [comment]
Indeed, it seems to be hardcoded frame indexes. The prologue event has a line located at 021C6AF8 that checks if Arikado's current frame index is 0xC, and spawns the knife then.
Because my darkFunction exporter/importer only preserves frame indexes when they are not part of any animation, that frame winds up getting changed to frame index 0x20.

Unfortunately, I can't think of any possible way to fix this. You call them "optimizations", but that's not true, it's simply that darkFunction's format doesn't allow me to preserve all of the information I need. A frame can't be in an animation and also have a name used to keep track of its original index. As a result, the order of the frames winds up being different after exporting and importing.

It's most likely not possible to fix while still using darkFunction. The proper solution here would be to code a proper GUI for editing sprites into DSVEdit's built in sprite editor so no conversion is necessary, but the GUI coding necessary to make that editor actually usable is too complex, so I won't do that.

The easy solution to your problem is to just edit that one line of code to use the new frame index instead of the original.

**Comment by piratesephiroth** [comment]
I understand that darkfunction doesn't support that but could you make the program write it as comments to the file?
Even if it wasn't able to fix it in the reimport process, it would at least point us in the right direction

**Comment by LagoLunatic** [comment]
I could write anything I wanted in comments of the anim file, since it's just xml.
But it wouldn't help anything since when you open and resave the anim file in darkFunction, darkFunction won't preserve those comments.
It would only allow preserving more information in the case where you click "Export" and immediately click "Import" without making any changes, so it's pointless.

**Comment by piratesephiroth** [comment]
yeah, but could you just write comments pointing that the event checks for this and that specific frame indexes.

Even if we had to fix it manually by editing the code.

**Comment by LagoLunatic** [comment]
I think you're underestimating how much work that would take. Just finding that one hardcoded frame index check I told you about took like 15-20 minutes of reading through code. It would probably take hundreds of hours of work manually reading through all of the game's code for me to compile a complete list of *every* hardcoded frame index in every enemy AI, cutscene, special object, NPC, etc. You're free to do that if you want to but I won't.

You may be able to automate the process by writing a script to parse through all of the game's code, but it won't give as accurate results as if done manually and would still take some work to write the script.

**Comment by piratesephiroth** [comment]
ah that's what I feared

**Comment by piratesephiroth** [comment]
well, it works

https://cdn.discordapp.com/attachments/478455683025469440/710529153849491506/output.mp4
