### ISSUE TITLE
Problem with importing darkfunction sprite

### ISSUE THREAD

**Issue by watermelonsplash666** [LagoLunatic/DSVEdit#32]
Hey Lago,
I had a problem importing dark function sprite in Castlevania AOS. I find that sections of my map were messed up after importing. Moreover, I tried to fix those areas using Tiled. Though the map is fixed, the weapon's sprite becomes invisible in the game. The weapon that I chose to edit is poison fist. Thank you very much for your help.
![image (2)](https://user-images.githubusercontent.com/62620477/87607164-90daf080-c6b1-11ea-8df8-07ebeaef2abb.png)
![image (1)](https://user-images.githubusercontent.com/62620477/87607165-91738700-c6b1-11ea-9694-9780a8e36ffd.png)

**Comment by LagoLunatic** [comment]
Have you ever deleted or moved the _dsvedit_freespace.txt file in your project directory? If you did File -> Extract ROM on a non-vanilla ROM, that could also effectively get rid of _dsvedit_freespace.txt since that information isn't stored inside the ROM itself, only in the text file.

Basically what I think happened is:
* You expanded the size of that room compared to vanilla, which means DSVEdit had to use free space for that room's new size.
* Then you deleted _dsvedit_freespace.txt, meaning you made DSVEdit forget what is and is not free space.
* Then you edited this sprite, and DSVEdit needed more free space, so it looked for it - and it found that space which was already being used for your long room, although DSVEdit didn't know that.
* DSVEdit avoided overwriting the parts of your room which have blocks in them, but it couldn't tell the difference between the empty space at the bottom of your room and legitimate free space, so it used that to put the sprite in, resulting in the corrupted stuff you see in your screenshot.

If that is what you did, you should ideally revert to a backup of your romhack from before deleting _dsvedit_freespace.txt and avoid deleting it again in the future.

**Comment by watermelonsplash666** [comment]
Ok, Thank you very much

**Comment by watermelonsplash666** [comment]
Problem solved, Thank you so much Lago!
