### ISSUE TITLE
AoS: Adding entities causes other entities to not load

### ISSUE THREAD

**Issue by EliteSoba** [LagoLunatic/DSVEdit#38]
#### Expected Behavior
Adding an entity should not affect the existence of other entities in the room and all entities, including the new one, should load when visiting the room

#### Actual Behavior
For some rooms, adding an entity will cause the last entity in the entity list to not load. Adding two entities will still only cause the last one to not load.

#### Reproduction steps
Add a meaningful entity to the Arena gargoyle hall (Sector 8, Room 0x0E, address 0x0851ED60) and test the room. Whichever entity is last on the entity list will not load.

#### Additional Info
This is probably more a question than an actual bug. In the gargoyle hall described above, setting the last entity in the list to `Instaload: 1` will successfully cause it to appear, but I couldn't find any documentation on how instaload works or why it's necessary for some rooms but not others.

Another example is adding a Bat to Castle Corridor Room 0x14 (address 0x0850FB9C). Adding the bat causes the three upper candles to never load, even when setting every entity in the room to Instaload 1, but replacing those candles with just about any other type of entity will cause the new entities to load.

**Comment by LagoLunatic** [comment]
Whoops... I guess I forgot ruby's sort function is unstable the last time I was fixing a AoS entity sorting bug and made things worse.

**Comment by LagoLunatic** [comment]
For future reference, the reason the order of the entities matters is because the GBA games linearly load entities from one end of the room to the other for performance reasons. When DSVEdit has an entity-sorting bug in it like this, it can wind up loading entities in the wrong order, such as the order the user added them to the room.
"Instaload" just tells the game engine to not use this performance optimization for that particular entity.

**Comment by EliteSoba** [comment]
Hmm, I guess that makes enough sense. If I were to edit the file without using this tool, would appending an entity to the end of the list and setting instaload to 1 (after moving the entity list to free space and whatnot) ensure all entities get loaded, or would the instaload mess with the entity loading order of the rest of the room?

I still don't quite understand the Bat example, but it seems to work if you change the destructables to other entity types or change the Bat to pretty much anything else, so I won't question it too much.

**Comment by LagoLunatic** [comment]
> Hmm, I guess that makes enough sense. If I were to edit the file without using this tool, would appending an entity to the end of the list and setting instaload to 1 (after moving the entity list to free space and whatnot) ensure all entities get loaded, or would the instaload mess with the entity loading order of the rest of the room?

Not sure

> I still don't quite understand the Bat example, but it seems to work if you change the destructables to other entity types or change the Bat to pretty much anything else, so I won't question it too much.

Oh sorry, I didn't test the bat example because I just assumed it was the same thing without reading it.
It's unrelated to entity order. The GBA just literally doesn't have enough memory to load the GFX data for all those entity types. Nothing will fix that, you have to delete another type of entity.

**Comment by EliteSoba** [comment]
All right, thanks for all the explanations.
