### ISSUE TITLE
Bypass data overwriting

### ISSUE THREAD

**Issue by watermelonsplash666** [LagoLunatic/DSVEdit#44]
Hi Lagolunatic,

I have used your editor for almost two years now, and it worked like a charm for me, as always. Thank you so much for your contribution. Upon recently, I have encountered an issue when working with Castlevania Aria of Sorrow. Before extracting the rom file with Dsv, I relocated a tileset and its collision's pointer to a new unused location using a hex editor to fit them in. When I try to import some Darkfunction animations, the free space that I have used for my tilesets is overwritten and corrupted. Is there any way to bypass data overwriting? By that means, is there a way to tell Dsv that the space is already used, please skip it? Thank you so much for your help!!

New Tileset data offset: 0068E000-0ADE
New Collision data offset: 0068F000-0253
I have used crystaltile before editing with Dsv:D

**Comment by LagoLunatic** [comment]
Yes, just edit the _dsvedit_freespace.txt file as explained in the readme. Update the offset and size, moving the free space down to wherever it should be in your project, instead of the vanilla values.

Note that you must do this before the corruption has happened, you can't fix it afterwards. Revert to a backup from before it was corrupted.
