### ISSUE TITLE
Adding GFX

### ISSUE THREAD

**Issue by cocytuswhisper** [LagoLunatic/DSVEdit#6]
First of all, thank you so much for this! It's really awesome, and I've been having a great time playing with it.

I was wondering, though -- it's possible to _edit_ gfx, and that's super cool, but is it possible to add entirely new gfx so that you can, say, add new enemies? Similarly, would it be possible to add new gfx into an existing sprite's list of gfx so that it can draw on them?

**Comment by LagoLunatic** [comment]
Unfortunately it's not possible to add new GFX files. Every GFX file needs to be registered in the game's list of assets, and there's no way realistic way to add new assets to that list as far as I know, since pointers to the list are hardcoded into the engine.

The same applies to a lot of other things - you can't add new sprite files, enemies, items, etc. You need to replace existing ones instead.

>Similarly, would it be possible to add new gfx into an existing sprite's list of gfx so that it can draw on them?

That would be doable, you would just need to repoint the list of GFX pointers to free space so you can add new pointers to the list.
But also note that if an enemy originally had exactly 1 GFX file, then there's no list and instead the enemy just hardcodes its single GFX pointer. In this case you would need to create a new GFX list in free space, then modify the enemy's create code to use this new list, and to call the LoadSpriteMultiGfx function instead of LoadSpriteSingleGfx.
I'm not planning on adding this into DSVEdit though since it seems like it would be very limited in use when adding new GFX files is impossible.

**Comment by cocytuswhisper** [comment]
That's too bad, but thank you very much for letting me know!
