### ISSUE TITLE
Options I like and others that don't exist DSV

### ISSUE THREAD

**Issue by wesley00x** [LagoLunatic/DSVEdit#63]
good night lagolunatic group, I liked the DSV Editor, but it still has limitations, not an option, that instead of editing the existing items, add more new items to the list of (items, weapons, armor and accessories?) , and an option that instead of also editing the existing monsters to put new ones in AoS?, for example Gremilin and Ukoback are the same monster in other games in the Castlevania series, but in AoS (Aria of Sorrow), Gremilin is the Gargoyle dyed green, and the real Gremilin (Ukoback), has the most useless ability in the game, I wanted to change that and exclude the existence of the Gargoyle with green skin, I really want to improve AoS and send the current Konami to the abyss, maybe they won't read this in full, but I admire the fact that it's easy to edit at least.

**Comment by LagoLunatic** [comment]
> good night lagolunatic group

I'm not a group

> instead of editing the existing items, add more new items to the list of (items, weapons, armor and accessories?) , and an option that instead of also editing the existing monsters to put new ones in AoS?

Adding new items instead of editing existing ones would require relocating all of the item lists elsewhere to free space and updating pointers to them, as well as updating all hardcoded checks on item global ID values as those would be shifted around by adding a new item. This would be difficult due to how many pointers/item IDs in the code would need to be found. I recommend replacing existing items instead of trying to add new ones.

> for example Gremilin and Ukoback are the same monster in other games in the Castlevania series, but in AoS (Aria of Sorrow), Gremilin is the Gargoyle dyed green, and the real Gremilin (Ukoback), has the most useless ability in the game, I wanted to change that and exclude the existence of the Gargoyle with green skin, I really want to improve AoS and send the current Konami to the abyss, maybe they won't read this in full, but I admire the fact that it's easy to edit at least.

I didn't understand a single thing you just said but good luck with whatever that is
