### ISSUE TITLE
Importing the manticore boss room of aria of sorrow from tiled causes a visual glitch

### ISSUE THREAD

**Issue by fcard** [LagoLunatic/DSVEdit#82]
Tested from the latest source.  Can be reproduced by simply importing from tiled with no changes.
It also already looks like this in the editor itself
Room ID is 06 08511DCC, in the chapel.
![built_rom_aos-0](https://github.com/LagoLunatic/DSVEdit/assets/12222927/70cb5811-ff16-4862-97bc-08519258b6cb)

**Comment by LagoLunatic** [comment]
The bug was that DSVEdit recalculates the width in pixels and height in pixels of each layer based on the number of screens wide/tall it is, but that seems to be incorrect specifically for AoS layers that have scroll mode C or D, so now I've changed it to skip doing this in those cases.

If you ever need to change the number of screens wide/tall a layer that has scroll modes C or D in AoS is, you may have to manually adjust the pixel widths/heights by opening it in Tiled and editing the new Tiled-only fields `layer_width_in_pixels` and `layer_height_in_pixels`.
